function(libsshpp_enable_sanitizers target)
    if(NOT LIBSSHPP_SANITIZERS)
        return()
    endif()
    set(_flags "")
    foreach(_san IN LISTS LIBSSHPP_SANITIZERS)
        string(APPEND _flags "-fsanitize=${_san} ")
    endforeach()
    separate_arguments(_flag_list UNIX_COMMAND "${_flags}")
    target_compile_options(${target} PUBLIC ${_flag_list} -fno-omit-frame-pointer)
    target_link_options(${target} PUBLIC ${_flag_list})
endfunction()
